[2022-06-18 07:58:25,055] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: simple_etl_dag.run_tables_exists_task manual__2022-06-18T07:57:54.452230+00:00 [queued]>
[2022-06-18 07:58:25,149] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: simple_etl_dag.run_tables_exists_task manual__2022-06-18T07:57:54.452230+00:00 [queued]>
[2022-06-18 07:58:25,152] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-06-18 07:58:25,155] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-06-18 07:58:25,156] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-06-18 07:58:25,213] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): run_tables_exists_task> on 2022-06-18 07:57:54.452230+00:00
[2022-06-18 07:58:25,223] {standard_task_runner.py:52} INFO - Started process 2574 to run task
[2022-06-18 07:58:25,232] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'simple_etl_dag', 'run_tables_exists_task', 'manual__2022-06-18T07:57:54.452230+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/simple_etl.py', '--cfg-path', '/tmp/tmpnnfqod04', '--error-file', '/tmp/tmpo7d_dlmk']
[2022-06-18 07:58:25,236] {standard_task_runner.py:77} INFO - Job 3: Subtask run_tables_exists_task
[2022-06-18 07:58:25,400] {logging_mixin.py:109} INFO - Running <TaskInstance: simple_etl_dag.run_tables_exists_task manual__2022-06-18T07:57:54.452230+00:00 [running]> on host b7a0af5ee6a4
[2022-06-18 07:58:25,711] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=simple_etl_dag
AIRFLOW_CTX_TASK_ID=run_tables_exists_task
AIRFLOW_CTX_EXECUTION_DATE=2022-06-18T07:57:54.452230+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-18T07:57:54.452230+00:00
[2022-06-18 07:58:25,722] {logging_mixin.py:109} INFO - >>> Running 'tables_exists' function. Logged at 2022-06-18 07:58:25.722121+00:00
[2022-06-18 07:58:25,726] {logging_mixin.py:109} INFO - >>> Running 'connect_db' function. Logged at 2022-06-18 07:58:25.726319+00:00
[2022-06-18 07:58:25,729] {logging_mixin.py:109} INFO - Connecting to DB
[2022-06-18 07:58:25,777] {logging_mixin.py:109} INFO - >>> Function: 'connect_db' executed. Logged at 2022-06-18 07:58:25.726319+00:00
[2022-06-18 07:58:25,781] {logging_mixin.py:109} INFO - Checking if tables exists
[2022-06-18 07:58:25,788] {logging_mixin.py:109} INFO - >>> Running 'check_table_exists' function. Logged at 2022-06-18 07:58:25.788151+00:00
[2022-06-18 07:58:25,814] {logging_mixin.py:109} INFO - 'raw_wine_quality_dataset' exists in the DB!
[2022-06-18 07:58:25,821] {logging_mixin.py:109} INFO - >>> Function: 'check_table_exists' executed. Logged at 2022-06-18 07:58:25.788151+00:00
[2022-06-18 07:58:25,826] {logging_mixin.py:109} INFO - >>> Running 'check_table_exists' function. Logged at 2022-06-18 07:58:25.825954+00:00
[2022-06-18 07:58:25,844] {logging_mixin.py:109} INFO - 'clean_wine_quality_dataset' exists in the DB!
[2022-06-18 07:58:25,855] {logging_mixin.py:109} INFO - >>> Function: 'check_table_exists' executed. Logged at 2022-06-18 07:58:25.825954+00:00
[2022-06-18 07:58:25,869] {logging_mixin.py:109} INFO - >>> Function: 'tables_exists' executed. Logged at 2022-06-18 07:58:25.722121+00:00
[2022-06-18 07:58:25,877] {python.py:175} INFO - Done. Returned value was: None
[2022-06-18 07:58:25,985] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=simple_etl_dag, task_id=run_tables_exists_task, execution_date=20220618T075754, start_date=20220618T075825, end_date=20220618T075825
[2022-06-18 07:58:26,100] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-06-18 07:58:26,240] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
